### ISSUE TITLE
Transformation of models with stereotype antipatterns

### ISSUE THREAD

**Issue by grbeni** [IncQueryLabs/mdk#1]
This issue tracks the ongoing work of transforming block diagrams with the stereotype antipattern demonstrated by Ivan Gomes.

The antipattern is depicted by the following figure.
![kep](https://user-images.githubusercontent.com/10759835/28523753-10f8081c-707e-11e7-9908-3c02ce765557.png)
Note the stereotype _MassedElement_ that is applied to all blocks. This stereotype has a tag definition _mass_ which can be set in all the corresponding blocks with an arbitrary default value (cannot be seen in the diagram). The problem with this pattern is that it encumbers manageability and analysis.

The following figure depicts the structure that should be used instead.
![kep](https://user-images.githubusercontent.com/10759835/28524188-ba2641aa-707f-11e7-8af4-bea78fa4f9ef.png)
Here value properties are used instead of stereotype tags. All values can have a default value (explicitly seen in the diagram). Moreover, a value of a block must redefine the same property value of the parent block (_redefines mass_) possibly with a different default value. This pattern supports manageability and analysis.

**Comment by lunkpeter** [comment]
Resolved by #2
