### ISSUE TITLE
Improve UX of MDK JSON features

### ISSUE THREAD

**Issue by bergmanngabor** [IncQueryLabs/mdk#8]
- [x] `<cameomodelname>.mdkmodel`
 - [x] Autoselect target directory to be the same as the model file
 - [x] Autosave whenever saving mdzip (is this possible via `SaveParticipant`?)

**Comment by danielsiegl** [comment]
Sound good too me

**Comment by bergmanngabor** [comment]
These are now done. A boolean flag was added to Project Options; if it is turned on, then the mdkmodel file will be automatically exported upon save (for local projects).
![image](https://user-images.githubusercontent.com/1148904/134712844-c709e12c-a282-40db-8296-7d2e40e89840.png)
