### ISSUE TITLE
CLI model patch application

### ISSUE THREAD

**Issue by bergmanngabor** [IncQueryLabs/mdk#9]
Create a commanline call that allows LemonTree after the merge to update the mdzip with the mdkpatch file – would make everything more user friendly

**Comment by danielsiegl** [comment]
Process:
Commandline Call  with *mdzip and *mdkpatch and mdkmodel as parameters

MAGIC Happens

Result an UPDATED mdzip and mdkmodel are on disc again - might rename *mdkpatch to *mdkpatch.bat ??

Exit if no mdkpatch exists

**Comment by bergmanngabor** [comment]
What I actually implemented:
 - inputs are a local MD project (`.mdzip` file path) and a patch file; no .mdkmodel is taken as input, as specified by the CLI arguments
 - the project is loaded
 - the project is patched with the patch
 - the project is saved
 - if Project Options are set up so that an `.mdkmodel` auto-export is enabled, it will happen.
 - a log in HTML format will be saved as `MDNotificationWindowText.html` in the working directory (this is done consistently with other MDK CLI actions), but of course if  the `-verbose` argument is specified, then everything will be logged to the console as well

What I did NOT do:
 - "Exit if no mdkpatch exists" --> please do not start MD if you have no patch file and have nothing to do... it takes too long... just check existence in whatever shell script you start MD from
 - "mdkmodel as parameters" --> no point, project is read from mdzip as normal

How to use: 
 - Please follow this guide on how to start MD command-line actions (specifically this is a **Plugin batch program**, not a **core*** one): https://docs.nomagic.com/display/MD190SP4/Specifying+batch+mode+program+classpath+and+required+system+properties
 - in order to start MD in a way that this CLI action is selected, please specify JVM arguments
        ```
        -Dcom.nomagic.magicdraw.launcher=com.nomagic.magicdraw.commandline.CommandLineActionLauncher
        -Dcom.nomagic.magicdraw.commandline.action=gov.nasa.jpl.mbee.mdk.cli.AutomatedPatchApplier
        ```
 - CLI input arguments to put at the end (after the main class `ProductionFrameworkLauncher`) that are passed on to the CLI patch action:  `-patchFile <path-to-patch-file>` and `-projectFile <path-to-mdzip>`


To calibrate expectations: starting MD and loading/saving projects is still slow when run from CLI.

**Comment by danielsiegl** [comment]
Can you pls provide a *.bat or a full commandline example

**Comment by bergmanngabor** [comment]
@danielsiegl by your request, the newest commit adds a .bat (as well as .sh) file to make running the CLI function easier.

**Prerequisite**: 
Set the envvar JAVA_HOME to point to a Java 8 installation

**Usage**:  
`%MAGICDRAW_HOME%\bin\cli\automatedpatchapplier.bat [-h] [-verbose] [-debug] -projectFile <path> -patchFile <path>` 
 
The batch file will return with an exit code ("error level") of 0 if and only if the patch was successfully applied, so that it is easily enbeddable in another script.
